### ISSUE TITLE
Connectivity Atlas Blog Post

### ISSUE THREAD

**Issue by mariano3** [developmentseed/connectivity-atlas#41]

**Comment by mariano3** [comment]
Hey guys, I'm going to start writing some thought toward the subject here to get some body copy for the post, as well as collect the necessary images. @jflasher @dmccarey

**Comment by jflasher** [comment]
:+1: Thanks! The About page might be a good starting point for a post.

http://atlas.developmentseed.org/about/

**Comment by mariano3** [comment]
I'm not the best at crafting these blog posts yet language wise but this intro on the site is pretty well formed in my opinion. ODes this need more info / different phrasing?:

Infrastructure connects us and defines us. The roads, pipelines and Internet cables that deliver our services also shape our opportunities, our vulnerabilities, and our identities. Political and geographic maps abound - yet there are few useful, elegant maps of the complex infrastructure that ties us. The Connectivity Atlas invites you to explore the shapes and lines that advance our global connectedness. We believe that great insight lies in these maps.

This is foremost a data project. It is frustratingly difficult to find usable geodata on infrastructure. This is surprising given the significant public and private resources that go toward building and maintaining this infrastructure. All of the data on the Connectivity Atlas is open and available for reuse. We invite you to participate by sharing and suggesting data to add.

The Connectivity Atlas was inspired by conversations between Parag Khanna and Development Seed. Snapshots from the Connectivity Atlas will be featured in Parag's upcoming book Mapping the Future (published by Penguin Random House in 2016).

**Comment by mariano3** [comment]
@jflasher @dmccarey  I'm not the best at crafting these blog posts yet language wise but this intro on the site is pretty well formed in my opinion. Does this need more info / different phrasing?:

Infrastructure connects us and defines us. The roads, pipelines and Internet cables that deliver our services also shape our opportunities, our vulnerabilities, and our identities. Political and geographic maps abound - yet there are few useful, elegant maps of the complex infrastructure that ties us. The Connectivity Atlas invites you to explore the shapes and lines that advance our global connectedness. We believe that great insight lies in these maps.

This is foremost a data project. It is frustratingly difficult to find usable geodata on infrastructure. This is surprising given the significant public and private resources that go toward building and maintaining this infrastructure. All of the data on the Connectivity Atlas is open and available for reuse. We invite you to participate by sharing and suggesting data to add.

The Connectivity Atlas was inspired by conversations between Parag Khanna and Development Seed. Snapshots from the Connectivity Atlas will be featured in Parag's upcoming book Mapping the Future (published by Penguin Random House in 2016).
